spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/graduateDesigne
    username: root
    password: 200208092733.Tzh

# 开启驼峰命名和下划线命名的自动转换,让数据库中的user_id可以映射到实体类中的userId
mybatis:
  configuration:
    map-underscore-to-camel-case: true
